export type ArsoFunction =
  | 'PILOTO_COMANDO'
  | 'COPILOTO'
  | 'COMISSARIO_VOO'
  | 'MECANICO_VOO'
  | 'MECANICO_MANUTENCAO_AERONAUTICA'
  | 'DESPACHANTE_OPERACIONAL_VOO'
  | 'OPERADOR_TRATOR_RAMPA_AEROPORTO'
  | 'AGENTE_PROTECAO_AVSEC';

export type ToxicologicalResult = 'NEGATIVO' | 'POSITIVO' | 'INCONCLUSIVO';
export type ArsoStatus = 'ATIVO' | 'SUSPENDED' | 'INACTIVE';

export const PPSP_CONSTANTS = {
  LONG_WINDOW_EXAM_VALIDITY_DAYS: 90,
  EXPIRATION_ALERT_DAYS_BEFORE: 15,
  RANDOM_SAMPLING_ANNUAL_MINIMUM_PERCENT: 0.25, // 25% por ano
} as const;

export const TRACKED_SUBSTANCES = [
  'ALCOOL_ETILICO',
  'CANABINOIDES',
  'COCAINA',
  'OPIACEOS',
  'ANFETAMINAS',
  'FENCICLIDINA',
] as const;

export const PHASE_4_PPSP_EVENTS = {
  ARSO_REGISTERED: 'ARSO_REGISTERED',
  TOXICOLOGICAL_EXAM_LOGGED: 'TOXICOLOGICAL_EXAM_LOGGED',
  RANDOM_SAMPLE_DRAWN: 'RANDOM_SAMPLE_DRAWN',
  ARSO_SUSPENDED: 'ARSO_SUSPENDED',
  ARSO_REINSTATED: 'ARSO_REINSTATED',
} as const;
