worker_processes auto;
events { worker_connections 1024; }
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;
  server_tokens off;
  gzip on;
  server {
    listen 8080;
    root /srv/shell;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
    add_header Access-Control-Allow-Origin "*" always;

    location /remotes/rconta/ { alias /srv/remotes/rconta/; }
    location /remotes/catalogo/ { alias /srv/remotes/catalogo/; }
    location /remotes/rloja/ { alias /srv/remotes/rloja/; }
    location /remotes/recrutamento/ { alias /srv/remotes/recrutamento/; }
    location /remotes/mro/ { alias /srv/remotes/mro/; }
    location /remotes/ops/ { alias /srv/remotes/ops/; }
    location /remotes/training/ { alias /srv/remotes/training/; }
    location /remotes/airport/ { alias /srv/remotes/airport/; }
    location / { try_files $uri $uri/ /index.html; }
  }
}
