import { forwardRef, useEffect, useId, useState, type ButtonHTMLAttributes, type HTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from 'react';
import { AlertCircle, CheckCircle2, LoaderCircle, X } from 'lucide-react';

const cn = (...classes: ReadonlyArray<string | false | null | undefined>): string => classes.filter(Boolean).join(' ');

export const Button = forwardRef<HTMLButtonElement, ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'danger' }>(({ className, variant = 'primary', ...props }, ref) => <button ref={ref} className={cn('inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50', variant === 'primary' && 'bg-[var(--vtx-primary)] text-white hover:bg-[var(--vtx-primary-hover)]', variant === 'secondary' && 'border border-[var(--vtx-border)] bg-[var(--vtx-surface)] text-[var(--vtx-text)]', variant === 'ghost' && 'bg-transparent hover:bg-[var(--vtx-primary-soft)]', variant === 'danger' && 'bg-[var(--vtx-danger)] text-white', className)} {...props} />);
Button.displayName = 'Button';

export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(({ className, ...props }, ref) => <input ref={ref} className={cn('min-h-10 w-full rounded-lg border border-[var(--vtx-border)] bg-[var(--vtx-surface)] px-3 py-2 text-sm text-[var(--vtx-text)] shadow-sm', className)} {...props} />);
Input.displayName = 'Input';
export const Select = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(({ className, children, ...props }, ref) => <select ref={ref} className={cn('min-h-10 w-full rounded-lg border border-[var(--vtx-border)] bg-[var(--vtx-surface)] px-3 py-2 text-sm', className)} {...props}>{children}</select>);
Select.displayName = 'Select';
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement>>(({ className, ...props }, ref) => <textarea ref={ref} className={cn('min-h-28 w-full rounded-lg border border-[var(--vtx-border)] bg-[var(--vtx-surface)] px-3 py-2 text-sm', className)} {...props} />);
Textarea.displayName = 'Textarea';

export const Checkbox = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>((props, ref) => <input ref={ref} type="checkbox" className="size-4 accent-[var(--vtx-primary)]" {...props} />);
Checkbox.displayName = 'Checkbox';
export const Radio = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>((props, ref) => <input ref={ref} type="radio" className="size-4 accent-[var(--vtx-primary)]" {...props} />);
Radio.displayName = 'Radio';
export const Switch = ({ checked, onCheckedChange, label }: { checked: boolean; onCheckedChange: (value: boolean) => void; label: string }) => <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={() => onCheckedChange(!checked)} className={cn('relative h-6 w-11 rounded-full transition', checked ? 'bg-[var(--vtx-primary)]' : 'bg-slate-400')}><span className={cn('absolute top-1 size-4 rounded-full bg-white transition', checked ? 'left-6' : 'left-1')} /></button>;

export const Badge = ({ children, tone = 'neutral', className }: { children: ReactNode; tone?: 'neutral' | 'success' | 'warning' | 'danger' | 'info'; className?: string }) => <span className={cn('inline-flex rounded-full px-2.5 py-1 text-xs font-semibold', tone === 'neutral' && 'bg-slate-100 text-slate-700', tone === 'success' && 'bg-emerald-100 text-emerald-800', tone === 'warning' && 'bg-amber-100 text-amber-800', tone === 'danger' && 'bg-red-100 text-red-800', tone === 'info' && 'bg-sky-100 text-sky-800', className)}>{children}</span>;
export const Card = ({ className, ...props }: HTMLAttributes<HTMLDivElement>) => <div className={cn('rounded-xl border border-[var(--vtx-border)] bg-[var(--vtx-surface)] p-5 shadow-[var(--vtx-shadow-sm)]', className)} {...props} />;
export const Table = ({ children }: { children: ReactNode }) => <div className="overflow-x-auto rounded-xl border border-[var(--vtx-border)]"><table className="w-full border-collapse text-left text-sm">{children}</table></div>;

export const Modal = ({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) => {
  useEffect(() => { const listener = (event: KeyboardEvent) => event.key === 'Escape' && onClose(); if (open) document.addEventListener('keydown', listener); return () => document.removeEventListener('keydown', listener); }, [open, onClose]);
  if (!open) return null;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" role="presentation" onMouseDown={(event) => event.currentTarget === event.target && onClose()}><section role="dialog" aria-modal="true" aria-label={title} className="w-full max-w-lg rounded-xl bg-[var(--vtx-surface)] p-6 shadow-2xl"><header className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><Button variant="ghost" aria-label="Fechar" onClick={onClose}><X size={18} /></Button></header>{children}</section></div>;
};
export const Drawer = ({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) => open ? <div className="fixed inset-0 z-50 bg-slate-950/50" role="presentation" onMouseDown={(event) => event.currentTarget === event.target && onClose()}><aside role="dialog" aria-label={title} className="ml-auto h-full w-full max-w-md bg-[var(--vtx-surface)] p-6 shadow-2xl"><header className="mb-6 flex justify-between"><h2 className="text-xl font-bold">{title}</h2><Button variant="ghost" onClick={onClose}><X size={18} /></Button></header>{children}</aside></div> : null;

export const Tabs = ({ tabs, active, onChange }: { tabs: readonly { id: string; label: string }[]; active: string; onChange: (id: string) => void }) => <div role="tablist" className="flex gap-1 border-b border-[var(--vtx-border)]">{tabs.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={active === tab.id} className={cn('border-b-2 px-4 py-3 text-sm font-semibold', active === tab.id ? 'border-[var(--vtx-primary)] text-[var(--vtx-primary)]' : 'border-transparent text-[var(--vtx-text-muted)]')} onClick={() => onChange(tab.id)}>{tab.label}</button>)}</div>;
export const Accordion = ({ title, children }: { title: string; children: ReactNode }) => <details className="rounded-lg border border-[var(--vtx-border)] bg-[var(--vtx-surface)] p-4"><summary className="cursor-pointer font-semibold">{title}</summary><div className="pt-3 text-sm text-[var(--vtx-text-muted)]">{children}</div></details>;
export const Tooltip = ({ label, children }: { label: string; children: ReactNode }) => <span className="group relative inline-flex">{children}<span role="tooltip" className="pointer-events-none absolute bottom-full left-1/2 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-slate-950 px-2 py-1 text-xs text-white group-hover:block group-focus-within:block">{label}</span></span>;

export const Toast = ({ tone = 'success', children }: { tone?: 'success' | 'error'; children: ReactNode }) => <div role="status" className="flex items-center gap-2 rounded-lg border border-[var(--vtx-border)] bg-[var(--vtx-surface)] p-3 shadow-lg">{tone === 'success' ? <CheckCircle2 className="text-emerald-600" /> : <AlertCircle className="text-red-600" />}{children}</div>;
export const Avatar = ({ name, src }: { name: string; src?: string }) => src ? <img className="size-9 rounded-full object-cover" src={src} alt={name} /> : <span className="grid size-9 place-items-center rounded-full bg-[var(--vtx-primary-soft)] text-sm font-bold text-[var(--vtx-primary)]" aria-label={name}>{name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span>;
export const Skeleton = ({ className }: { className?: string }) => <div aria-hidden="true" className={cn('animate-pulse rounded-lg bg-slate-200 dark:bg-slate-700', className)} />;
export const Spinner = ({ label = 'Carregando' }: { label?: string }) => <span role="status" className="inline-flex items-center gap-2"><LoaderCircle className="animate-spin" size={18} /><span>{label}</span></span>;
export const EmptyState = ({ title, description, action }: { title: string; description: string; action?: ReactNode }) => <div className="grid min-h-48 place-items-center rounded-xl border border-dashed border-[var(--vtx-border)] p-8 text-center"><div><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm text-[var(--vtx-text-muted)]">{description}</p>{action && <div className="mt-4">{action}</div>}</div></div>;
export const Pagination = ({ page, totalPages, onChange }: { page: number; totalPages: number; onChange: (page: number) => void }) => <nav aria-label="Paginação" className="flex items-center justify-between gap-4"><Button variant="secondary" disabled={page <= 1} onClick={() => onChange(page - 1)}>Anterior</Button><span className="text-sm">Página {page} de {totalPages}</span><Button variant="secondary" disabled={page >= totalPages} onClick={() => onChange(page + 1)}>Próxima</Button></nav>;

export const Field = ({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: ReactNode }) => { const id = useId(); return <label htmlFor={id} className="grid gap-1.5 text-sm font-semibold"><span>{label}</span><span id={id}>{children}</span>{hint && !error && <small className="font-normal text-[var(--vtx-text-muted)]">{hint}</small>}{error && <small className="font-normal text-[var(--vtx-danger)]">{error}</small>}</label>; };
export const ThemeToggle = () => { const [dark, setDark] = useState(false); const toggle = (value: boolean) => { setDark(value); document.documentElement.dataset.theme = value ? 'dark' : 'light'; }; return <Switch label="Alternar tema escuro" checked={dark} onCheckedChange={toggle} />; };
