DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'vortex_app') THEN
    CREATE ROLE vortex_app NOSUPERUSER NOCREATEDB NOCREATEROLE NOLOGIN NOBYPASSRLS;
  END IF;
END
$$;

GRANT vortex_app TO CURRENT_USER;

GRANT USAGE ON SCHEMA identity, professional, stock, recruitment, ledger, protocol, oauth TO vortex_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA identity TO vortex_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA identity TO vortex_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA professional TO vortex_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA stock TO vortex_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA recruitment TO vortex_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ledger TO vortex_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA protocol TO vortex_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA oauth TO vortex_app;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA identity TO vortex_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA professional TO vortex_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA stock TO vortex_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA recruitment TO vortex_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ledger TO vortex_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA protocol TO vortex_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA oauth TO vortex_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO vortex_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA professional GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO vortex_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA stock GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO vortex_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA recruitment GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO vortex_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ledger GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO vortex_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA protocol GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO vortex_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA oauth GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO vortex_app;

ALTER TABLE identity.people FORCE ROW LEVEL SECURITY;
ALTER TABLE identity.companies FORCE ROW LEVEL SECURITY;
ALTER TABLE identity.relationships FORCE ROW LEVEL SECURITY;
ALTER TABLE identity.tenant_members FORCE ROW LEVEL SECURITY;
ALTER TABLE professional.profiles FORCE ROW LEVEL SECURITY;
ALTER TABLE stock.holdings FORCE ROW LEVEL SECURITY;
ALTER TABLE stock.items FORCE ROW LEVEL SECURITY;
ALTER TABLE recruitment.vacancies FORCE ROW LEVEL SECURITY;
ALTER TABLE recruitment.applications FORCE ROW LEVEL SECURITY;
ALTER TABLE ledger.ledger_blocks FORCE ROW LEVEL SECURITY;
ALTER TABLE protocol.protocols FORCE ROW LEVEL SECURITY;
